config/routes.rb
Rails.application.routes.draw do
  resources :course_registrations
  resources :charges, only: [:new, :create]
  resources :courses do 
    collection do 
      get :new_course_enrollment
      post :create_course_enrollment
    end
  end
  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords", :omniauth_callbacks => "users/omniauth_callbacks"}
  root 'home#index'

  get 'home/index'

  devise_scope :user do
    post 'social_info'=> 'users/omniauth_callbacks#social_info'
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json

  respond_to :js

  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
   @course = Course.find(params[:id])
  end
  
  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        stripe = StripeIntegrationClass.new
        product = stripe.create_stripe_product(@course.name, @course.course_fee)
        @course.update(stripe_product_id: product.id )
        puts product
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        stripe = StripeIntegrationClass.new
        pr = stripe.update_stripe_product(@course.stripe_product_id, @course.name)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    stripe = StripeIntegrationClass.new
    stripe.destroy_stripe_product(@course.stripe_product_id)
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_course_enrollment
    @course = Course.find(params[:course_id])
    respond_to do |format| 
      format.js {'courses/new_course_enrollment'}
    end
  end

  def create_course_enrollment
    @enrollment = CourseRegistration.new(enrollment_params)
    @enrollment.save
    @enrollment.update_attributes(:stripe_token => params[:stripeToken], :stripe_token_type => params[:stripeTokenType], :email => params[:stripeEmail])
    stripe = StripeIntegrationClass.new
    customer = stripe.create_stripe_customer(params[:stripeToken],params[:stripeEmail])
    c = stripe.retrieve_customer_stripe(customer.id)
    cu = stripe.list_customer_stripe()
    Customer.create(stripe_customer_email: customer.email, stripe_customer_id: customer.id)
    puts c
  redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :course_fee)
    end

    def enrollment_params
      params.require(:create_course_enrollment).permit(:first_name, :last_name, :contact, :course_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :course_fee %><br>
    <%= f.number_field :course_fee %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/_new_course_enrollment.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Modal title</h4>
    </div>
    <div class="modal-body">
      <%= form_for :create_course_enrollment, url: :create_course_enrollment_courses, method: "post" do |f| %>
       <%= f.hidden_field :course_id, :value => @course.id %>
        <div class="field">
          <%= f.label :first_name %><br>
          <%= f.text_field :first_name %>
        </div>
        <div class="field">
          <%= f.label :last_name %><br>
          <%= f.text_field :last_name %>
        </div>
        <div class="field">
          <%= f.label :contact %><br>
          <%= f.text_field :contact %>
        </div>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.application.secrets.stripe_publishable_key %>"
        data-description="subscription for <%= @course.name %>"
        data-amount="<%= @course.course_fee %>"
        data-locale="auto"></script>
      <% end %>

    </div>
  </div>
</div>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Course fee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.course_fee %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/new_course_enrollment.js.erb
$("#course-enrollment").html("<%= escape_javascript render(:partial => 'courses/new_course_enrollment') %>")

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to "Enroll into this course", new_course_enrollment_courses_path(course_id: @course.id), class: "btn btn-primary", remote: true, "data-toggle" => "modal", "data-target" => "#course-enrollment" %>


<div class="modal fade" id="course-enrollment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
</div>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>