config/routes.rb
Rails.application.routes.draw do
  resources :course_registrations
  resources :charges, only: [:new, :create]
  resources :courses do 
    collection do 
      get :new_course_enrollment
      post :create_course_enrollment
    end
  end
  devise_for :users, controllers: {sessions: "users/sessions", registrations: "users/registrations", passwords: "users/passwords", :omniauth_callbacks => "users/omniauth_callbacks"}
  root 'home#index'

  get 'home/index'

  devise_scope :user do
    post 'social_info'=> 'users/omniauth_callbacks#social_info'
  end

end

app/models/course_registration.rb
class CourseRegistration < ActiveRecord::Base
  belongs_to :course
end

app/controllers/course_registrations_controller.rb
class CourseRegistrationsController < ApplicationController
  before_action :set_course_registration, only: [:show, :edit, :update, :destroy]

  # GET /course_registrations
  # GET /course_registrations.json
  def index
    @course_registrations = CourseRegistration.all
  end

  # GET /course_registrations/1
  # GET /course_registrations/1.json
  def show
  end

  # GET /course_registrations/new
  def new
    @course_registration = CourseRegistration.new
  end

  # GET /course_registrations/1/edit
  def edit
  end

  # POST /course_registrations
  # POST /course_registrations.json
  def create
    @course_registration = CourseRegistration.new(course_registration_params)

    respond_to do |format|
      if @course_registration.save
        format.html { redirect_to @course_registration, notice: 'Course registration was successfully created.' }
        format.json { render :show, status: :created, location: @course_registration }
      else
        format.html { render :new }
        format.json { render json: @course_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /course_registrations/1
  # PATCH/PUT /course_registrations/1.json
  def update
    respond_to do |format|
      if @course_registration.update(course_registration_params)
        format.html { redirect_to @course_registration, notice: 'Course registration was successfully updated.' }
        format.json { render :show, status: :ok, location: @course_registration }
      else
        format.html { render :edit }
        format.json { render json: @course_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_registrations/1
  # DELETE /course_registrations/1.json
  def destroy
    @course_registration.destroy
    respond_to do |format|
      format.html { redirect_to course_registrations_url, notice: 'Course registration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course_registration
      @course_registration = CourseRegistration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_registration_params
      params.require(:course_registration).permit(:first_name, :last_name, :email, :contact, :course_id,)
    end
end

app/helpers/course_registrations_helper.rb
module CourseRegistrationsHelper
end

app/views/course_registrations/_form.html.erb
<%= form_for(@course_registration) do |f| %>
  <% if @course_registration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course_registration.errors.count, "error") %> prohibited this course_registration from being saved:</h2>

      <ul>
      <% @course_registration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :contact %><br>
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.text_field :course_id %>
  </div>
  <!-- <div class="actions">
    <%= f.submit %>
  </div> -->
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.application.secrets.stripe_publishable_key %>"
          data-description="A month's subscription"
          data-amount="7500"
          data-locale="auto"></script>
<% end %>

app/views/course_registrations/edit.html.erb
<h1>Editing Course Registration</h1>

<%= render 'form' %>

<%= link_to 'Show', @course_registration %> |
<%= link_to 'Back', course_registrations_path %>

app/views/course_registrations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Course Registrations</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Contact</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @course_registrations.each do |course_registration| %>
      <tr>
        <td><%= course_registration.first_name %></td>
        <td><%= course_registration.last_name %></td>
        <td><%= course_registration.email %></td>
        <td><%= course_registration.contact %></td>
        <td><%= course_registration.course %></td>
        <td><%= link_to 'Show', course_registration %></td>
        <td><%= link_to 'Edit', edit_course_registration_path(course_registration) %></td>
        <td><%= link_to 'Destroy', course_registration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course registration', new_course_registration_path %>

app/views/course_registrations/new.html.erb
<h1>New Course Registration</h1>

<%= render 'form' %>

<%= link_to 'Back', course_registrations_path %>

app/views/course_registrations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @course_registration.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @course_registration.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @course_registration.email %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @course_registration.contact %>
</p>

<p>
  <strong>Course:</strong>
  <%= @course_registration.course %>
</p>

<%= link_to 'Edit', edit_course_registration_path(@course_registration) %> |
<%= link_to 'Back', course_registrations_path %>